remote_theme: "jekyll/minima"

minima:
  social_links:
    - title: github
      icon: github
      url: "https://github.com/subeenregmi"
    - title: youtube
      icon: youtube
      url: "https://youtube.com/@subeenregmi"
